[tool.flake8]
application-import-names = "about,catalog,core,download,feedback,homepage,lyceum,statistics_app,rating,users"
import-order-style = "google"

exclude = "venv, .venv, .env, .git, __pycache__, db.json, migrations, manage.py"
max-line-length = 79
inline-quotes = "double"

forbidden-imports = "inspect,sys"
forbidden-functions = """
*: datetime.datetime.now, we use django utils
*: sys.path.append, usage of sys.path is banned
*: globals, usage of globals is banned
*: locals, usage of locals is banned
"""


disable-noqa = true

[tool.black]
line-length = 79
